version: "3.4"

services:
  solr:
    image: intranda/goobi-viewer-docker-solr
    volumes:
      - type: bind
        source: ${SOLR_DATA_DIR}
        target: /var/solr
      - type: bind
        source: ./solr/goobiviewer
        target: /opt/goobiviewer
    environment:
      - ZK_HOST=zookeeper:2181
      - SOLR_HEAP=2048m
      - GC_TUNE=-XX:SurvivorRatio=4 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=8 -XX:+UseConcMarkSweepGC -XX:ConcGCThreads=4 -XX:ParallelGCThreads=4 -XX:+CMSScavengeBeforeRemark -XX:PretenureSizeThreshold=64m -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=50 -XX:CMSMaxAbortablePrecleanTime=6000 -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled
      - SOLR_LOG_LEVEL=ERROR
      - TZ=${TZ}
      # for further configuration check documentation of official Solr docker image
    depends_on:
      - zookeeper
    restart: unless-stopped

  zookeeper:
    image: zookeeper:3.6.3
    volumes:
      - type: bind
        source: ${ZOOKEEPER_DATA_DIR}
        target: /data
      - type: bind
        source: ${ZOOKEEPER_DATALOG_DIR}
        target: /datalog
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  viewer:
    image: ${VIEWER_IMAGE}
    environment:
      TZ: ${TZ}
      DB_USER: ${DB_VIEWER_USER}
      DB_PASSWORD: ${DB_VIEWER_PASSWORD}
      VIEWER_DOMAIN: ${VIEWER_DOMAIN}
      # DB_SERVER: viewer-db
      # DB_PORT: 3306
      # SOLR_URL: http://solr:8983/solr/collection1
    depends_on:
      - viewer-db
      - solr
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${VIEWER_DIR}
        target: /opt/digiverso/viewer
      - type: bind
        source: ${VIEWER_LOGDIR}
        target: /opt/digiverso/logs/

  viewer-db:
    image: mariadb:10.5
    environment:
      TZ: ${TZ}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_VIEWER_DATABASE}
      MYSQL_USER: ${DB_VIEWER_USER}
      MYSQL_PASSWORD: ${DB_VIEWER_PASSWORD}
    volumes:
      - type: bind
        source: ${DB_DATA_DIR}
        target: /var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    restart: unless-stopped

  indexer:
    image: intranda/goobi-viewer-indexer
    # environment:
    #   SOLR_URL:  http://solr:8983/solr/collection1
    #   VIEWER_URL: http://viewer:8080/viewer
    depends_on:
      - solr
    restart: unless-stopped
    volumes:
      - type: bind
        source: ${VIEWER_DIR}
        target: /opt/digiverso/viewer/
      - type: bind
        source: ${VIEWER_LOGDIR}
        target: /opt/digiverso/logs/
    environment:
      - TZ=${TZ}
  proxy:
    image: intranda/goobi-viewer-docker-proxy
    environment:
      SERVERNAME: ${VIEWER_DOMAIN}
      TZ: ${TZ}
      # HTTPD_PORT: 80
      # SERVERADMIN: support@intranda.com
      # REMOTEIP_HEADER: X-Forwarded-For
      # REMOTEIP_INTERNAL_PROXY: ""
      # USE_MOD_REMOTEIP: 0
      # SITEMAP_LOCATION: ""
      # VIEWER_HTTP_PORT: 8080
      # VIEWER_AJP_PORT: 8009
      # VIEWER_PATH: /viewer
      # VIEWER_CONTAINER: viewer
      # SOLR_PORT: 8983
      # SOLR_PATH: /solr
      # SOLR_CONTAINER: solr
      # SOLR_INCLUDES: "Require all denied"
    ports:
      - 80:80
    restart: unless-stopped
