version: "3.4"

services:
  indexer:
    volumes:
      - type: bind
        source: ${INDEXER_CONFIG}
        target: /opt/digiverso/indexer/solr_indexerconfig.xml
   proxy:
    environment:
      SITEMAP_LOCATION: https://${VIEWER_DOMAIN}/viewer/sitemap_index.xml
