version: "3.4"

services:
  indexer:
    volumes:
      - type: bind
        source: ${INDEXER_CONFIG}
        target: /opt/digiverso/indexer/config_indexer.xml
  proxy:
    environment:
      SITEMAP_LOCATION: https://${VIEWER_DOMAIN}/viewer/sitemap_index.xml
      #
      # CATALINA_OPTS: "-Xmx4G"
      #
      # SOLR_INCLUDES: > # set further parameters for SOLR Webinterface acces, e.g.:
      #   Require ip 10.10.10.10 # allow access from IP 10.10.10.10
      # USE_MOD_REMOTEIP: 1 # this enables mod_remoteip (possibly needed if using a reverse proxy)
      # REMOTEIP_INTERNAL_PROXY: 172.23.0.254 # IP address of the external reverse proxy
      #
      # Example configuration for making a directory available via the web server:
      # volumes:
      #   - type: bind
      #     source: /opt/digiverso/additional_web_dir/
      #     target: /var/www/additional_web_dir/
      #     read_only: true
      #
      #
      # Example configurtion for a multiline custom config snippet. Please note, that $ symbols
      # need to be escaped by another $ symbol:
      #
      # CUSTOM_CONFIG: |
      #   RedirectMatch /content/(.*)\$$ https://viewer.example.org/viewer/content/$$1
      #   RewriteCond %{REQUEST_URI} ^/cms/ppnresolver/$$
      #   RewriteCond %{QUERY_STRING} ^(.*)$$
      #   RewriteRule ^(.*)$$ https://viewer.example.org/viewer/ppnresolver?id=%1 [R=302,L]
